//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.01.03 at 06:19:16 PM CET 
//


package sumobindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for locationType complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="locationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="netOffset"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;pattern value="(\-)?(\d+.?|(\d*.\d+)),(\-)?(\d+.?|(\d*.\d+))"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="convBoundary"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;pattern value="(\-)?(\d+.?|(\d*.\d+)),(\-)?(\d+.?|(\d*.\d+)),(\-)?(\d+.?|(\d*.\d+)),(\-)?(\d+.?|(\d*.\d+))"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="origBoundary"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;pattern value="(\-)?(\d+.?|(\d*.\d+)),(\-)?(\d+.?|(\d*.\d+)),(\-)?(\d+.?|(\d*.\d+)),(\-)?(\d+.?|(\d*.\d+))"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="projParameter" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "locationType")
public class LocationType {

    @XmlAttribute(name = "netOffset")
    protected String netOffset;
    @XmlAttribute(name = "convBoundary")
    protected String convBoundary;
    @XmlAttribute(name = "origBoundary")
    protected String origBoundary;
    @XmlAttribute(name = "projParameter", required = true)
    protected String projParameter;

    /**
     * Gets the value of the netOffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetOffset() {
        return netOffset;
    }

    /**
     * Sets the value of the netOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetOffset(String value) {
        this.netOffset = value;
    }

    /**
     * Gets the value of the convBoundary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConvBoundary() {
        return convBoundary;
    }

    /**
     * Sets the value of the convBoundary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConvBoundary(String value) {
        this.convBoundary = value;
    }

    /**
     * Gets the value of the origBoundary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigBoundary() {
        return origBoundary;
    }

    /**
     * Sets the value of the origBoundary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigBoundary(String value) {
        this.origBoundary = value;
    }

    /**
     * Gets the value of the projParameter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjParameter() {
        return projParameter;
    }

    /**
     * Sets the value of the projParameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjParameter(String value) {
        this.projParameter = value;
    }

}
