//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.01.03 at 06:19:16 PM CET 
//


package sumobindings;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for netType complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="netType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="location" type="{}locationType"/&gt;
 *         &lt;element name="type" type="{}typeType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="edge" type="{}edgeType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="tlLogic" type="{}tlLogicType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="junction" type="{}junctionType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="connection" type="{}connectionType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="prohibition" type="{}prohibitionType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="roundabout" type="{}roundaboutType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="taz" type="{}tazType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="version"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;pattern value="\d+.\d+"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="junctionCornerDetail" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="junctionLinkDetail" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="lefthand" type="{}boolType" /&gt;
 *       &lt;attribute name="rectangularLaneCut" type="{}boolType" /&gt;
 *       &lt;attribute name="walkingareas" type="{}boolType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name="net")
@XmlType(name = "netType", propOrder = {
    "location",
    "type",
    "edge",
    "tlLogic",
    "junction",
    "connection",
    "prohibition",
    "roundabout",
    "taz"
})
public class NetType {

    @XmlElement(required = true)
    protected LocationType location;
    protected List<TypeType> type;
    protected List<EdgeType> edge;
    protected List<TlLogicType> tlLogic;
    protected List<JunctionType> junction;
    protected List<ConnectionType> connection;
    protected List<ProhibitionType> prohibition;
    protected List<RoundaboutType> roundabout;
    protected List<TazType> taz;
    @XmlAttribute(name = "version")
    protected String version;
    @XmlAttribute(name = "junctionCornerDetail")
    protected Integer junctionCornerDetail;
    @XmlAttribute(name = "junctionLinkDetail")
    protected Integer junctionLinkDetail;
    @XmlAttribute(name = "lefthand")
    protected String lefthand;
    @XmlAttribute(name = "rectangularLaneCut")
    protected String rectangularLaneCut;
    @XmlAttribute(name = "walkingareas")
    protected String walkingareas;

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link LocationType }
     *     
     */
    public LocationType getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationType }
     *     
     */
    public void setLocation(LocationType value) {
        this.location = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the type property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeType }
     * 
     * 
     */
    public List<TypeType> getType() {
        if (type == null) {
            type = new ArrayList<TypeType>();
        }
        return this.type;
    }

    /**
     * Gets the value of the edge property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the edge property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEdge().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EdgeType }
     * 
     * 
     */
    public List<EdgeType> getEdge() {
        if (edge == null) {
            edge = new ArrayList<EdgeType>();
        }
        return this.edge;
    }

    /**
     * Gets the value of the tlLogic property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tlLogic property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTlLogic().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TlLogicType }
     * 
     * 
     */
    public List<TlLogicType> getTlLogic() {
        if (tlLogic == null) {
            tlLogic = new ArrayList<TlLogicType>();
        }
        return this.tlLogic;
    }

    /**
     * Gets the value of the junction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the junction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJunction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JunctionType }
     * 
     * 
     */
    public List<JunctionType> getJunction() {
        if (junction == null) {
            junction = new ArrayList<JunctionType>();
        }
        return this.junction;
    }

    /**
     * Gets the value of the connection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the connection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConnection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConnectionType }
     * 
     * 
     */
    public List<ConnectionType> getConnection() {
        if (connection == null) {
            connection = new ArrayList<ConnectionType>();
        }
        return this.connection;
    }

    /**
     * Gets the value of the prohibition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prohibition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProhibition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProhibitionType }
     * 
     * 
     */
    public List<ProhibitionType> getProhibition() {
        if (prohibition == null) {
            prohibition = new ArrayList<ProhibitionType>();
        }
        return this.prohibition;
    }

    /**
     * Gets the value of the roundabout property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roundabout property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoundabout().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RoundaboutType }
     * 
     * 
     */
    public List<RoundaboutType> getRoundabout() {
        if (roundabout == null) {
            roundabout = new ArrayList<RoundaboutType>();
        }
        return this.roundabout;
    }

    /**
     * Gets the value of the taz property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taz property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaz().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TazType }
     * 
     * 
     */
    public List<TazType> getTaz() {
        if (taz == null) {
            taz = new ArrayList<TazType>();
        }
        return this.taz;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the junctionCornerDetail property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getJunctionCornerDetail() {
        return junctionCornerDetail;
    }

    /**
     * Sets the value of the junctionCornerDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setJunctionCornerDetail(Integer value) {
        this.junctionCornerDetail = value;
    }

    /**
     * Gets the value of the junctionLinkDetail property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getJunctionLinkDetail() {
        return junctionLinkDetail;
    }

    /**
     * Sets the value of the junctionLinkDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setJunctionLinkDetail(Integer value) {
        this.junctionLinkDetail = value;
    }

    /**
     * Gets the value of the lefthand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLefthand() {
        return lefthand;
    }

    /**
     * Sets the value of the lefthand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLefthand(String value) {
        this.lefthand = value;
    }

    /**
     * Gets the value of the rectangularLaneCut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRectangularLaneCut() {
        return rectangularLaneCut;
    }

    /**
     * Sets the value of the rectangularLaneCut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRectangularLaneCut(String value) {
        this.rectangularLaneCut = value;
    }

    /**
     * Gets the value of the walkingareas property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWalkingareas() {
        return walkingareas;
    }

    /**
     * Sets the value of the walkingareas property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWalkingareas(String value) {
        this.walkingareas = value;
    }

}
