//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.01.03 at 06:19:16 PM CET 
//


package sumobindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for splitType complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="splitType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="lanes"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;pattern value="\d+(([,;]|\s)\d+)*"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="pos" use="required" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *       &lt;attribute name="speed" type="{}positiveFloatType" /&gt;
 *       &lt;attribute name="type" type="{}nodeTypeType" /&gt;
 *       &lt;attribute name="tl" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="tlType" type="{}tlTypeType" /&gt;
 *       &lt;attribute name="shape" type="{}shapeType" /&gt;
 *       &lt;attribute name="radius" type="{}nonNegativeFloatType" /&gt;
 *       &lt;attribute name="keepClear" type="{}boolType" /&gt;
 *       &lt;attribute name="idBefore" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="idAfter" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "splitType")
public class SplitType {

    @XmlAttribute(name = "lanes")
    protected String lanes;
    @XmlAttribute(name = "pos", required = true)
    protected float pos;
    @XmlAttribute(name = "speed")
    protected Float speed;
    @XmlAttribute(name = "type")
    protected NodeTypeType type;
    @XmlAttribute(name = "tl")
    protected String tl;
    @XmlAttribute(name = "tlType")
    protected TlTypeType tlType;
    @XmlAttribute(name = "shape")
    protected String shape;
    @XmlAttribute(name = "radius")
    protected Float radius;
    @XmlAttribute(name = "keepClear")
    protected String keepClear;
    @XmlAttribute(name = "idBefore")
    protected String idBefore;
    @XmlAttribute(name = "idAfter")
    protected String idAfter;

    /**
     * Gets the value of the lanes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanes() {
        return lanes;
    }

    /**
     * Sets the value of the lanes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanes(String value) {
        this.lanes = value;
    }

    /**
     * Gets the value of the pos property.
     * 
     */
    public float getPos() {
        return pos;
    }

    /**
     * Sets the value of the pos property.
     * 
     */
    public void setPos(float value) {
        this.pos = value;
    }

    /**
     * Gets the value of the speed property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the speed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setSpeed(Float value) {
        this.speed = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link NodeTypeType }
     *     
     */
    public NodeTypeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link NodeTypeType }
     *     
     */
    public void setType(NodeTypeType value) {
        this.type = value;
    }

    /**
     * Gets the value of the tl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTl() {
        return tl;
    }

    /**
     * Sets the value of the tl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTl(String value) {
        this.tl = value;
    }

    /**
     * Gets the value of the tlType property.
     * 
     * @return
     *     possible object is
     *     {@link TlTypeType }
     *     
     */
    public TlTypeType getTlType() {
        return tlType;
    }

    /**
     * Sets the value of the tlType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TlTypeType }
     *     
     */
    public void setTlType(TlTypeType value) {
        this.tlType = value;
    }

    /**
     * Gets the value of the shape property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShape() {
        return shape;
    }

    /**
     * Sets the value of the shape property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShape(String value) {
        this.shape = value;
    }

    /**
     * Gets the value of the radius property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getRadius() {
        return radius;
    }

    /**
     * Sets the value of the radius property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setRadius(Float value) {
        this.radius = value;
    }

    /**
     * Gets the value of the keepClear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeepClear() {
        return keepClear;
    }

    /**
     * Sets the value of the keepClear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeepClear(String value) {
        this.keepClear = value;
    }

    /**
     * Gets the value of the idBefore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdBefore() {
        return idBefore;
    }

    /**
     * Sets the value of the idBefore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdBefore(String value) {
        this.idBefore = value;
    }

    /**
     * Gets the value of the idAfter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdAfter() {
        return idAfter;
    }

    /**
     * Sets the value of the idAfter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdAfter(String value) {
        this.idAfter = value;
    }

}
