//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.01.03 at 06:19:16 PM CET 
//


package sumobindings;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tazType complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tazType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tazSource" type="{}tazSubType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="tazSink" type="{}tazSubType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="edges" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="shape" type="{}shapeType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tazType", propOrder = {
    "tazSource",
    "tazSink"
})
public class TazType {

    protected List<TazSubType> tazSource;
    protected List<TazSubType> tazSink;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "edges")
    protected String edges;
    @XmlAttribute(name = "shape")
    protected String shape;

    /**
     * Gets the value of the tazSource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tazSource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTazSource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TazSubType }
     * 
     * 
     */
    public List<TazSubType> getTazSource() {
        if (tazSource == null) {
            tazSource = new ArrayList<TazSubType>();
        }
        return this.tazSource;
    }

    /**
     * Gets the value of the tazSink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tazSink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTazSink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TazSubType }
     * 
     * 
     */
    public List<TazSubType> getTazSink() {
        if (tazSink == null) {
            tazSink = new ArrayList<TazSubType>();
        }
        return this.tazSink;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the edges property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdges() {
        return edges;
    }

    /**
     * Sets the value of the edges property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdges(String value) {
        this.edges = value;
    }

    /**
     * Gets the value of the shape property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShape() {
        return shape;
    }

    /**
     * Sets the value of the shape property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShape(String value) {
        this.shape = value;
    }

}
