//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.01.03 at 06:19:16 PM CET 
//


package sumobindings;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeType complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="restriction" type="{}restrictionType"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="allow" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="disallow" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="numLanes" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="speed" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *       &lt;attribute name="discard" type="{}boolType" /&gt;
 *       &lt;attribute name="oneway" type="{}boolType" /&gt;
 *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *       &lt;attribute name="sidewalkWidth" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *       &lt;attribute name="bikeLaneWidth" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeType", propOrder = {
    "restriction"
})
public class TypeType {

    protected List<RestrictionType> restriction;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "allow")
    protected String allow;
    @XmlAttribute(name = "disallow")
    protected String disallow;
    @XmlAttribute(name = "priority")
    protected Integer priority;
    @XmlAttribute(name = "numLanes")
    protected Integer numLanes;
    @XmlAttribute(name = "speed")
    protected Float speed;
    @XmlAttribute(name = "discard")
    protected String discard;
    @XmlAttribute(name = "oneway")
    protected String oneway;
    @XmlAttribute(name = "width")
    protected Float width;
    @XmlAttribute(name = "sidewalkWidth")
    protected Float sidewalkWidth;
    @XmlAttribute(name = "bikeLaneWidth")
    protected Float bikeLaneWidth;

    /**
     * Gets the value of the restriction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the restriction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRestriction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RestrictionType }
     * 
     * 
     */
    public List<RestrictionType> getRestriction() {
        if (restriction == null) {
            restriction = new ArrayList<RestrictionType>();
        }
        return this.restriction;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the allow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllow() {
        return allow;
    }

    /**
     * Sets the value of the allow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllow(String value) {
        this.allow = value;
    }

    /**
     * Gets the value of the disallow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisallow() {
        return disallow;
    }

    /**
     * Sets the value of the disallow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisallow(String value) {
        this.disallow = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPriority(Integer value) {
        this.priority = value;
    }

    /**
     * Gets the value of the numLanes property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumLanes() {
        return numLanes;
    }

    /**
     * Sets the value of the numLanes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumLanes(Integer value) {
        this.numLanes = value;
    }

    /**
     * Gets the value of the speed property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the speed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setSpeed(Float value) {
        this.speed = value;
    }

    /**
     * Gets the value of the discard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscard() {
        return discard;
    }

    /**
     * Sets the value of the discard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscard(String value) {
        this.discard = value;
    }

    /**
     * Gets the value of the oneway property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOneway() {
        return oneway;
    }

    /**
     * Sets the value of the oneway property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOneway(String value) {
        this.oneway = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setWidth(Float value) {
        this.width = value;
    }

    /**
     * Gets the value of the sidewalkWidth property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getSidewalkWidth() {
        return sidewalkWidth;
    }

    /**
     * Sets the value of the sidewalkWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setSidewalkWidth(Float value) {
        this.sidewalkWidth = value;
    }

    /**
     * Gets the value of the bikeLaneWidth property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getBikeLaneWidth() {
        return bikeLaneWidth;
    }

    /**
     * Sets the value of the bikeLaneWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setBikeLaneWidth(Float value) {
        this.bikeLaneWidth = value;
    }

}
